use super::*;
fn command(label: &'static str, shortcut: &'static str, action: Action) -> Entry {
    Entry::Item(label, shortcut, Command::Edit(action))
}
pub(super) fn entries(index: usize) -> Vec<Entry> {
    use Entry::Separator as Sep;
    match index {
        0 => vec![
            command("New Canvas…", "Ctrl+N", Action::New),
            command("Open Project…", "Ctrl+O", Action::Open),
            command("Open PSD…", "", Action::OpenPsd),
            command("Open RAW…", "", Action::OpenRaw),
            command("Open from Clipboard", "", Action::OpenClipboard),
            command("Import Images…", "", Action::Import),
            Sep,
            command("Save", "Ctrl+S", Action::Save),
            command("Save As…", "Ctrl+Shift+S", Action::SaveAs),
            Sep,
            command("Export PNG…", "Ctrl+Shift+E", Action::ExportPng),
            command("Export TIFF…", "", Action::ExportTiff),
            command("Export WebP…", "", Action::ExportWebp),
            command("Export PSD…", "", Action::ExportPsd),
            command("Export JPEG…", "Ctrl+Alt+Shift+S", Action::ExportJpegFile),
            Sep,
            command("Close Project", "Ctrl+W", Action::CloseTab),
            Entry::Item("Quit Compositor", "Ctrl+Q", Command::Quit),
        ],
        1 => vec![
            command("Undo", "Ctrl+Z", Action::Undo),
            command("Redo", "Ctrl+Shift+Z", Action::Redo),
            Sep,
            command("Cut", "Ctrl+X", Action::Cut),
            command("Copy", "Ctrl+C", Action::Copy),
            command("Copy Merged", "Ctrl+Shift+C", Action::CopyMerged),
            command("Paste", "Ctrl+V", Action::Paste),
            Sep,
            command("Fill with Foreground Color", "Alt+Backspace", Action::Fill),
            command(
                "Fill with Background Color",
                "Ctrl+Backspace",
                Action::FillBackground,
            ),
            command("Clear Selection Pixels", "Delete", Action::Clear),
            command(
                "Content-Aware Fill…",
                "Shift+Backspace",
                Action::Filter(compositor::filters::Filter::ContentFill),
            ),
        ],
        3 => vec![
            command("All", "Ctrl+A", Action::SelectAll),
            command("Deselect", "Ctrl+D", Action::Deselect),
            command("Inverse", "Ctrl+Shift+I", Action::InvertSelection),
            command("Subject", "", Action::SelectSubject),
            command("Layer’s Pixels", "", Action::LoadAlpha),
            command("Mask’s Black Areas", "", Action::LoadMask),
            Sep,
            Entry::Item("Expand", "", Command::ResizeSelection { expand: true }),
            Entry::Item("Contract", "", Command::ResizeSelection { expand: false }),
            command("Feather…", "", Action::FeatherSelection),
        ],
        4 => vec![
            command("Curves…", "Ctrl+M", Action::AdjustPixels(Kind::Curves)),
            command("Levels…", "Ctrl+L", Action::AdjustPixels(Kind::Levels)),
            command(
                "Hue/Saturation…",
                "Ctrl+U",
                Action::AdjustPixels(Kind::HueSaturation),
            ),
            command("Exposure…", "", Action::AdjustPixels(Kind::Exposure)),
            command("Gradient Map…", "", Action::AdjustPixels(Kind::GradientMap)),
            command("Grain…", "", Action::AdjustPixels(Kind::Grain)),
            command("Invert", "Ctrl+I", Action::InvertPixels),
            Sep,
            command("Canvas Size…", "Ctrl+Alt+C", Action::CanvasSize),
            command("Image Size…", "Ctrl+Alt+I", Action::ImageSize),
            Sep,
            command("Flip Canvas Horizontal", "", Action::FlipCanvasX),
            command("Flip Canvas Vertical", "", Action::FlipCanvasY),
        ],
        5 => vec![
            command(
                "Gaussian Blur…",
                "",
                Action::Filter(compositor::filters::Filter::Gaussian { radius: 1. }),
            ),
            command(
                "Motion Blur…",
                "",
                Action::Filter(compositor::filters::Filter::Motion {
                    distance: 10.,
                    angle: 0.,
                }),
            ),
            command(
                "Add Noise…",
                "",
                Action::Filter(compositor::filters::Filter::Noise {
                    amount: 10.,
                    gaussian: false,
                    monochromatic: false,
                    seed: 0,
                }),
            ),
            command(
                "Lens Correction…",
                "",
                Action::Filter(compositor::filters::Filter::Lens { distortion: 0. }),
            ),
            command("Vignette…", "", Action::Filter(compositor::filters::Filter::Vignette(Default::default()))),
            command("Bloom / Glow…", "", Action::Filter(compositor::filters::Filter::Bloom { amount: 40., radius: 24. })),
            command("Remove Background…", "", Action::RemoveBackground),
        ],
        6 => vec![
            Entry::Submenu("New Adjustment Layer", 9),
            command("Edit Adjustment…", "", Action::EditAdjustment),
            command("Develop RAW…", "", Action::DevelopRaw),
            command("Rasterize RAW Layer", "", Action::RasterizeRaw),
            Sep,
            command("Transform Layer", "Ctrl+T", Action::Transform),
            command("Duplicate Layer", "Ctrl+J", Action::Duplicate),
            Sep,
            command("Create Clipping Mask", "Ctrl+Alt+G", Action::Clip),
            Sep,
            command("Group Selected Layers", "Ctrl+G", Action::Group),
            command("Move Out of Folder", "", Action::MoveOutOfGroup),
            command("New Blank Layer", "Ctrl+Shift+N", Action::AddLayer),
            command("Rename Layer…", "", Action::Rename),
            Entry::Item("Hide Layer", "", Command::Visibility),
            Sep,
            command("Move Layer Up", "Ctrl+]", Action::Raise),
            command("Move Layer Down", "Ctrl+[", Action::Lower),
            command("Merge Down", "Ctrl+E", Action::Merge),
            Sep,
            command("Flip Layer Horizontal", "", Action::FlipX),
            command("Flip Layer Vertical", "", Action::FlipY),
            Sep,
            command("Delete Layer", "", Action::DeleteLayer),
        ],
        2 => vec![
            command("Fit Canvas", "Ctrl+0", Action::Fit),
            command("Actual Pixels", "Ctrl+1", Action::Actual),
            command("Zoom In", "Ctrl++", Action::ZoomIn),
            command("Zoom Out", "Ctrl+-", Action::ZoomOut),
            Sep,
            command("Pixel Grid (800% and above)", "", Action::PixelGrid),
            command("Rulers", "Ctrl+R", Action::Rulers),
            command("Grid", "Ctrl+'", Action::Grid),
            command("Guides", "Ctrl+;", Action::Guides),
            Sep,
            command("Snap", "Ctrl+Shift+;", Action::Snap),
            Entry::Submenu("Snap To", 11),
            command("Lock Guides", "", Action::LockGuides),
            command("Clear Guides", "", Action::ClearGuides),
            Entry::Item("Show Transform Controls", "Ctrl+H", Command::Handles),
        ],
        7 => vec![
            Entry::Item("Keyboard Shortcuts…", "", Command::Shortcuts),
            Entry::Item("About Compositor", "", Command::About),
            Sep,
            Entry::Item("Check for Updates…", "", Command::Updates),
        ],
        8 => vec![
            command("Rename…", "", Action::Rename),
            command("Develop RAW…", "", Action::DevelopRaw),
            command("Rasterize RAW Layer", "", Action::RasterizeRaw),
            Entry::Item("Hide/Show Layer", "", Command::Visibility),
            command("Add White Mask", "", Action::AddMask),
            command("Add Black Mask", "", Action::HideMask),
            command("Enable/Disable Mask", "", Action::ToggleMask),
            command("Delete Mask", "", Action::DeleteMask),
            command("Release Clipping Mask", "", Action::Clip),
            command("Move Out of Folder", "", Action::MoveOutOfGroup),
            command("Delete Layer / Folder", "", Action::DeleteLayer),
        ],
        9 => vec![
            command(
                "Hue/Saturation…",
                "",
                Action::Adjustment(Kind::HueSaturation),
            ),
            command("Levels…", "", Action::Adjustment(Kind::Levels)),
            command("Curves…", "", Action::Adjustment(Kind::Curves)),
            command("Exposure…", "", Action::Adjustment(Kind::Exposure)),
            command("Gradient Map…", "", Action::Adjustment(Kind::GradientMap)),
            command("Grain…", "", Action::Adjustment(Kind::Grain)),
        ],
        11 => vec![
            command("Grid", "", Action::SnapGrid),
            command("Guides", "", Action::SnapGuides),
            command("Layers", "", Action::SnapLayers),
            command("Document Bounds", "", Action::SnapBounds),
        ],
        _ => Vec::new(),
    }
}
