use super::*;
use image::Rgba;

#[test]
fn defaults_preserve_continuous_rgb_and_every_alpha_exactly() {
    let settings = Vibrance::default();
    assert!(settings.identity());
    assert_eq!(settings.vibrance(), 0.);
    assert_eq!(settings.saturation(), 0.);
    let rgb = [0.1234567, 0.9876543, 0.0000123];
    assert_eq!(settings.apply_rgb(rgb), rgb);
    for alpha in 0..=255 {
        let pixel = [13, 219, 87, alpha];
        assert_eq!(settings.pixel(pixel), pixel);
    }
}

#[test]
fn output_matches_independent_camera_raw_c_samples() {
    // Outputs generated by calling the original AdjustPixels.c function with
    // these inputs. They cover skin protection, signed amounts and clipping.
    let samples = [
        ([0.6, 0.45, 0.3], 100., 0., [0.619341, 0.446841, 0.274341]),
        ([0.3, 0.45, 0.6], 100., 0., [0.23553, 0.46053, 0.68553]),
        ([0.6, 0.45, 0.3], -100., 0., [0.53553, 0.46053, 0.38553]),
        ([0.3, 0.45, 0.6], -100., 0., [0.36447, 0.43947, 0.51447]),
        (
            [0.7, 0.41, 0.26],
            47.25,
            -23.75,
            [0.66349056, 0.417_758_1, 0.29065513],
        ),
        (
            [0.7, 0.41, 0.26],
            47.25,
            83.75,
            [0.9492172, 0.35704228, 0.05074492],
        ),
        ([0.99, 0.9, 0.87], 100., 100., [1., 0.86472803, 0.75200075]),
        ([0.1, 0.9, 0.2], -100., -100., [0.67938; 3]),
    ];
    for (rgb, vibrance, saturation, expected) in samples {
        let actual = Vibrance::new(vibrance, saturation).unwrap().apply_rgb(rgb);
        for (a, b) in actual.into_iter().zip(expected) {
            assert!((a - b).abs() < 3e-7, "{rgb:?}: {actual:?} != {expected:?}");
        }
    }
}

#[test]
fn skin_protection_reduces_positive_boost_but_not_negative_reduction() {
    let chroma = |rgb: [f32; 3]| {
        rgb.into_iter().fold(f32::NEG_INFINITY, f32::max)
            - rgb.into_iter().fold(f32::INFINITY, f32::min)
    };
    let skin = [0.6, 0.45, 0.3];
    let blue = [0.3, 0.45, 0.6];
    let positive = Vibrance::new(100., 0.).unwrap();
    let negative = Vibrance::new(-100., 0.).unwrap();
    assert!(chroma(positive.apply_rgb(skin)) < chroma(positive.apply_rgb(blue)));
    assert!((chroma(negative.apply_rgb(skin)) - chroma(negative.apply_rgb(blue))).abs() < 1e-6);
}

#[test]
fn vibrance_leaves_neutrals_and_fully_saturated_colors_unchanged() {
    for amount in [-100., -37.5, 22.5, 100.] {
        let settings = Vibrance::new(amount, 0.).unwrap();
        for gray in 0..=255 {
            assert_eq!(
                settings.pixel([gray, gray, gray, 255]),
                [gray, gray, gray, 255]
            );
        }
        for rgb in [[255, 0, 0, 255], [0, 255, 0, 255], [0, 0, 255, 255]] {
            assert_eq!(settings.pixel(rgb), rgb);
        }
    }
}

#[test]
fn minimum_saturation_desaturates_with_rec709_luminance() {
    assert_eq!(
        Vibrance::new(0., -100.).unwrap().pixel([255, 0, 0, 99]),
        [54, 54, 54, 99]
    );
    assert_eq!(
        Vibrance::new(0., -100.).unwrap().pixel([0, 255, 0, 99]),
        [182, 182, 182, 99]
    );
    assert_eq!(
        Vibrance::new(0., -100.).unwrap().pixel([0, 0, 255, 99]),
        [18, 18, 18, 99]
    );
}

#[test]
fn image_processing_preserves_alpha_and_invisible_rgb_without_mutating_input() {
    let source = RgbaImage::from_fn(4, 2, |x, y| {
        Rgba([40 + 50 * y as u8, 100, 150, [0, 1, 100, 255][x as usize]])
    });
    let original = source.clone();
    let result = reference(&source, Vibrance::new(80., 20.).unwrap());
    assert_eq!(source, original);
    for (before, after) in source.pixels().zip(result.pixels()) {
        assert_eq!(before[3], after[3]);
        if before[3] == 0 {
            assert_eq!(before, after);
        }
    }
}

#[test]
fn settings_validate_construction_and_deserialization() {
    for (vibrance, saturation) in [(-100., 100.), (47.25, -23.75), (0., 0.)] {
        let settings = Vibrance::new(vibrance, saturation).unwrap();
        let encoded = serde_json::to_string(&settings).unwrap();
        assert_eq!(
            serde_json::from_str::<Vibrance>(&encoded).unwrap(),
            settings
        );
    }
    for value in [f32::NAN, f32::INFINITY, f32::NEG_INFINITY, -100.1, 100.1] {
        assert!(Vibrance::new(value, 0.).is_err());
        assert!(Vibrance::new(0., value).is_err());
    }
    for encoded in [
        r#"{"vibrance":101,"saturation":0}"#,
        r#"{"vibrance":0,"saturation":-101}"#,
        r#"{"vibrance":null,"saturation":0}"#,
        r#"{"vibrance":0}"#,
        r#"{"vibrance":0,"saturation":0,"extra":true}"#,
    ] {
        assert!(
            serde_json::from_str::<Vibrance>(encoded).is_err(),
            "{encoded}"
        );
    }
}

#[test]
fn editable_identity_preserves_f64_backdrop_without_f32_roundtrip() {
    let input = [0.1234567890123, 0.99999999999, 0.00000001234567, 0.6];
    assert_eq!(
        crate::adjustment::ExtendedAdjustment::Vibrance(Vibrance::default()).apply_rgba(input),
        input
    );
}
